### ISSUE TITLE
Adapting Lenza & Primiceri (2021) to SVARS

### ISSUE THREAD

**Issue by rayccg** [rayccg/Macroecom-RP#2]
Hi @donotdespair

Following your recommendation, I just finished by first reading of Lenza & Primiceri (2021) for estimating VARS post-COVID-19. 

My understanding is their proceure explicitly models the heightened volatility during the known pandemic period through a variable $s_t$, which is premultiplied to the VAR error term:

$$y_t = X_t\beta + s_t\varepsilon_t$$

But in order to estimate, the procedure transforms the data/divides both sides of the above equation with $s_t$ to arrive at:

$$\tilde{y_t} = \tilde{X_t}\beta + \varepsilon_t$$

However, since the SVAR models already involve their own transformations/manipulations between the structural and reduced form model, I am confused on where and how $s_t$ comes into the picture in the SVAR context. 

Hope you could give me guidance on how to proceed with this. Thank you.

Respectfully,
Ray

**Comment by donotdespair** [comment]
Cool @rayccg 

Thanks for submitting this issue!

So now your algo will estimate two groups of parameters:
- `A` and `\Sigma` (no LaTeX in md!) associated with the RF model
- and those associated with `s_t`

The transformation you described will allow you to estimate `A` and `\Sigma` conditionally on `s_t`, and `s_t` is estimated in its own special way via its marginal posterior by integrating out `A` and `\Sigma` analytically.

The estimation of the SF model follows this and is based on the `chol()` transformation of `\Sigma` in the first step. So, nothing more changes in your algos except for the accommodation of `s_t` in the RF model. Your SF model accommodates the Covid-related heteroskedasticity, though.

Does this help?

**Comment by rayccg** [comment]
Thank you, Tomasz.

I attempted some derivations based on your comments. Would it be okay if I dropped by your office to check with you?

**Comment by donotdespair** [comment]
Hey @rayccg Catch me tomorrow! Today, I was on a strike :)
