### ISSUE TITLE
Submission of Part 2 - Modelling Framework

### ISSUE THREAD

**Issue by rayccg** [rayccg/Macroecom-RP#4]
Dear @donotdespair

I just committed my submission for Part 2 - Modelling Framework (5254e4a6d0b28dbab481a51e09e08fdb1a6b30b0) and was hoping to submit it on LMS. However, the submission link seems to be closed. May I know how I should submit my work for Part 2?

Thank you very much.

Respectfully,
Ray

**Comment by donotdespair** [comment]
Thanks for letting me know, @rayccg!

I have now extended the availability of the assignements.
